services:
  api:
    build: .
    container_name: led-server-api
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb://mongo:27017/led-server
      - GOOGLE_SHEETS_URL=${GOOGLE_SHEETS_URL}
      - GOOGLE_SHEETS_SHEET_ID=${GOOGLE_SHEETS_SHEET_ID}
    # example firmware dir. change it or comment it out to disable firmware updates
    volumes:
      - ~/docker/LEDserver/firmware/:/app/server/build/firmware
    networks:
      - led-server
  mongo:
    image: mongo
    container_name: led-server-mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ~/docker/LEDserver/data/:/data/db
    networks:
      - led-server
networks:
  led-server:
    driver: bridge
