version: '3.8'
services:
  api:
    build: .
    container_name: led-server-api
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    networks:
      - led-server
  mongo:
    image: mongo
    container_name: led-server-mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - /home/server/docker/LEDserver/:/data/db
    networks:
      - led-server
networks:
  led-server:
    driver: bridge