version: '3.8'
services:
  api:
    build: .
    container_name: led-server-api
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: led-server-mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
networks:
  led-server:
    driver: bridge
volumes:
  mongodata:
